### ISSUE TITLE
Property loading from ConfigMap or Secret 

### ISSUE THREAD

**Issue by bouskaJ** [citrusframework/yaks#123]
YAKS is a tool for integration testing. Integration testing means that you could test integration between various systems and it can happen that you will need credentials to log in. We can introduce new section in yaks-config.yaml for loading properties from ConfigMap/Secret resource.

```
apiVersion: v1
data:
  secret-saas.properties: mySaaSCreds
kind: Secret
metadata:
  name: secret-saas
type: Opaque
```
```
config:
  namespace:
    temporary: true
  secret: secret-saas
  run: |
    oc create secret generic mock-secret-saas --from-file=secret-saas.properties -n ${YAKS_NAMESPACE}
   .....
```
```
Background: 
    Given URL: ${url_loaded_from_secret/ConfigMap}
    And HTTP request header Authorization is "Bearer ${token_from_secret}"
    And HTTP request header Content-Type is "application/json"
    And HTTP request body:  {  "Name" : "username" }

  Scenario:
    Given integration salesforce-to-workday is running
    When send POST /services/data/v20.0/sobjects/Account
    Then receive HTTP 201 Created
    And integration salesforce-to-workday should print Name: username
```
