### ISSUE TITLE
yaks-viewer role doesn't have camel-k resources

### ISSUE THREAD

**Issue by akihikokuroda** [citrusframework/yaks#254]
I ran the camel-k sample in OpneShift then I got the following error.  I'm using `YAKS 0.2.0`
```
integrations.camel.apache.org "helloworld" is forbidden: User "system:serviceaccount:integrationtest:yaks-viewer" cannot get resource "integrations" in API group "camel.apache.org" 
```
After adding 
```
  - verbs:
      - '*'
    apiGroups:
      - camel.apache.org
    resources:
      - '*'
```
in the yaks-viewer role, it worked without error.  I don't see any configuration instructions for the role.   Is this a doc issue or runtime issue?

Thanks!
