### ISSUE TITLE
Incompatible magic value 4022320623 in class file <.class> for page objects

### ISSUE THREAD

**Issue by NilsBerger** [citrusframework/yaks#323]
Hi!

I currently wanted to try out the page object for for more complex queries. Here is my page object class.

```
package com.XXX.XXX.yaks;

import com.consol.citrus.selenium.model.WebPage;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;

public class GoogleSearchPage implements WebPage {

    @FindBy(how = How.CSS, using = "input[name=q]")
    private WebElement searchInput;

    @FindBy(id = "username")
    private WebElement searchButton;

    public GoogleSearchPage() {
    }

    /**
     * Sets the user name.
     * @param value
     */
    public void setSearch(String value) {
        searchInput.clear();
        searchInput.sendKeys(value);
    }
    /**
     * Sets the user name.
     * @param value
     */
    public void clickEnterSearch() {
        searchInput.sendKeys(Keys.ENTER);
    }
} 

```
I compiled the java class and added it to the yaks-config.yaml

```
config:
  runtime:
    selenium:
      image: selenium/standalone-chrome:88.0
    env:
      - name: YAKS_SELENIUM_BROWSER_TYPE
        value: chrome
      - name: YAKS_SELENIUM_BROWSER_REMOTE_SERVER_URL
        value: http://localhost:4444/wd/hub
    resources:
      - GoogleSearchPage.class
```

When I run the test I get the following error "Failure caused by java.lang.ClassFormatError - Incompatible magic value 4022320623 in class file GoogleSearchPage". This is odd, because when I open the class in a hex editor I see the expected magic number CAFEBABE (3405691582), which is the expected magic number the Class.forName-method needs. 

When I however look at the content section of the add ressources I see ���� where I would expect the CAFEBABE value.
![image](https://user-images.githubusercontent.com/8149241/123272431-04ac8c80-d502-11eb-8cdf-1122350ecaf9.png)

Is this an error on the yaks side?
Should I create a maven repository for the page object and declare it as a dependency? Or what should I do for a working example?
Where is the file stored on the actual test pod, so I can check if the magic numbers add up?

Version: 0.4.0

Thanks for you help!
