### ISSUE TITLE
Pre/post script conditions

### ISSUE THREAD

**Issue by christophd** [citrusframework/yaks#341]
YAKS is able to run pre and post scripts as part of the test run. The script execution should be optional according to an `if` condition that gets evaluated. 

Possible script execution conditions are

* os type (linux, windows, darwin)
* environment variables

Conditions should be added to run/script steps in `yaks-config.yaml` something like:

```yaml
config:
  namespace:
    temporary: true
    autoRemove: true
pre:
  - if: os=windows
    script: prepare.sh
  - if: "env:regression=true"
    run: echo Starting regression! 
post:
  - if: os=windows
    script: finish.sh
  - if: "env:regression=true"
    run: echo Regression finished!
```
