### ISSUE TITLE
'Then receive Knative event' expects specific Ce-Id even though none is specified

### ISSUE THREAD

**Issue by zeidlerb** [citrusframework/yaks#359]
## Expected Behavior

When not specifying the _Ce-Id_ property for the `Then receive Knative event` step, YAKS should not check the _Ce-Id_ when validating the received event and, barring any other issues, the test should succeed.

## Current Behavior

The test fails with the message:

`Validation failed: Values not equal for header element 'Ce-Id' expected 'yaks-test-event' but was 'C7BAD03F65E6AFB-0000000000000208'`

## Steps to Reproduce

Feature used:

```gherkin
Feature: Deploy a Camel Application that can send Events

  Scenario Outline: Make sure Events are sent
    Given Kubernetes namespace camel-demo
     And Knative broker URL: http://broker-ingress.knative-eventing.svc.cluster.local/camel-demo/default 
     And create Knative event consumer service yaks-event-service
     And create Knative trigger yaks-event-trigger on service yaks-event-service
     And Knative event consumer timeout is 30000 milliseconds
    Then receive Knative event
    | type            | camel.test.event |
```

Event that was sent, as seen by an Eventdisplay:

```yaml
☁️  cloudevents.Event
Validation: valid
Context Attributes,
  specversion: 1.0
  type: camel.test.event
  source: route1
  id: C7BAD03F65E6AFB-0000000000000283
  time: 2021-12-30T10:51:49.467Z
Extensions,
  knativearrivaltime: 2021-12-30T10:51:49.46917162Z
Data,
  Hello Camel K from yaml
```

## Context (Environment)

Used Version:
* YAKS Operator Version: 0.7.0
* YAKS CLI Version: 0.7.0
* Knative Eventing: v0.28.0

Mitigation of this problem is difficult, since the `Ce-Id` is being autogenerated outside of the test context and can therefore not be anticipated.
