### ISSUE TITLE
"append-to-viewer"-Tag not working

### ISSUE THREAD

**Issue by nhb-89** [citrusframework/yaks#360]
Hi!

I currently want to create configmaps in the namespace **yaks-ns-2** from a yaks test running in the namespace **yaks-ns-1**. Or to make is short; this command should return yes -->
`kubectl auth can-i create configmaps --namespace yaks-ns-2 --as system:serviceaccount:yaks-ns-1:yaks-viewer`

My sample code looks as follows.

kubernetes.feature
```
Feature: Test

  Scenario:

    Given Kubernetes namespace yaks-ns-2
    Given create Kubernetes resource
    """
    apiVersion: v1
    kind: ConfigMap
    metadata:
        name: game-demo
        namespace: yaks-ns-2
    data:
        player_initial_lives: "3"  
    """
```

yaks-config.yaml

```
config:
  operator:
    roles:
    - role.yaml
    - role-binding.yaml
  namespace:
    name: yaks-ns-1
    temporary: false
    autoRemove: false
```

role.yaml
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yaks-operator-config
  namespace: yaks-ns-2
  labels:
    app: "yaks"
    yaks.citrusframework.org/append-to-viewer: "true"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
```

role-binding.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yaks-operator-config
  namespace: yaks-ns-2
  labels:
    app: "yaks"
    yaks.citrusframework.org/append-to-viewer: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yaks-operator-config
subjects:
- kind: ServiceAccount
  name: yaks-operator
  namespace: yaks-ns-1
```

The test fails if I run it with following error "User "system:serviceaccount:yaks-ns-1:yaks-viewer" cannot create resource "configmaps" in API group "" in the namespace "yaks-ns-2"."

I also tried out the following commands

yaks role --add role.yaml
yaks role --add role-binding.yaml

yaks role --add role.yaml -n yaks-ns-1
yaks role --add role-binding.yaml -n yaks-ns-1

yaks role --add role.yaml -n yaks-ns-2
yaks role --add role-binding.yaml -n yaks-ns-2

What am I doing wrong?
