### ISSUE TITLE
Improve Reporting

### ISSUE THREAD

**Issue by Inithron** [citrusframework/yaks#490]
Hi,
Is there a possibility to use the Cucumber Json Plugin together with YAKS?
I have tried following cases in the yaks-config.yaml:

1. 
```
config:
  runtime:
    cucumber:
      plugin:
      - "pretty"
      - "json:cucumber.json"
```
2. 
```
config:
  runtime:
    cucumber:
      options: "--format json:cucumber.json"
```
I was not able to verify if the cucumber.json file was really created. But even if this would be the case, how could I get this file out of the test pod? Reason for this question: I would like to use the [Cucumber Reports Plugin](https://plugins.jenkins.io/cucumber-reports/) which creates the pretty HTML reports out of this file.
